extension["Huntersxy"]={
	intro:"烤箱插座阴间武将",
	author:"huntersxy",
	netdisk:"",
	forum:"",
	version:"1.3",
	files:["格蕾修.jpg","LICENSE","cvhanser.jpg","h_bronya.jpg","extension.js.bak","h_spuyuan.jpg","h_jiaxu.jpg","h_smaliang.jpg","h_huohuo.jpg","h_huohuoweiba.jpg","h_ailixiya.jpg","h_gx.jpg","格蕾修.jpg"],
	size:"625KB"
};